### ISSUE TITLE
`rad test` failing on a clean project

### ISSUE THREAD

**Issue by bcpeinhardt** [tynanbe/rad#3] opened 2023-04-25 19:25 UTC
Hey there!
I created a clean gleam project using gleam new, installed rad and added a bash alias to my .bashrc, and then ran `rad test`, which led to the following error
```
  Targeting erlang...
file:///home/benjaminp/fuckabout/radalicious/build/dev/javascript/shellout/shellout_ffi.mjs:65
    return result.isOk() ? result[0] : false;
                  ^

TypeError: Cannot read properties of undefined (reading 'isOk')
    at getBool (file:///home/benjaminp/fuckabout/radalicious/build/dev/javascript/shellout/shellout_ffi.mjs:65:19)
    at os_command (file:///home/benjaminp/fuckabout/radalicious/build/dev/javascript/shellout/shellout_ffi.mjs:75:18)
    at file:///home/benjaminp/fuckabout/radalicious/build/dev/javascript/shellout/shellout.mjs:305:12
    at Module.command (file:///home/benjaminp/fuckabout/radalicious/build/dev/javascript/shellout/shellout.mjs:306:5)
    at file:///home/benjaminp/fuckabout/radalicious/build/dev/javascript/rad/rad_ffi.mjs:63:14

Node.js v19.8.1
```

Is `rad test` supposed to work right away or am I supposed to configure a task in the gleam.toml?

**Comment by tynanbe** [comment] 2023-05-29 18:54
Thanks for the report!

Sorry for the delay, this issue was actually caused by the JavaScript ffi `map` update in `gleam_stdlib` v0.28. [Shellout](https://github.com/tynanbe/shellout)'s JS ffi was affected, but the issue has been resolved in its latest release (see https://github.com/tynanbe/shellout/commit/a4e30ad7b308e1d2df753ca31b8e409f7b38fcd9).

Rad has also been updated to use the latest version of [shellout](https://github.com/tynanbe/shellout).

**Closed as completed** 2023-05-29 18:54 UTC
